// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edeauveswbzhztmpcdsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkZWF1dmVzd2J6aHp0bXBjZHNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNjQ2OTIsImV4cCI6MjA3Mjg0MDY5Mn0.T3hN2aK31muA3V9PKf0CUA4ZAyRLetTC488PbyqMOmM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});